name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: lines, bytes-size
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_days: 30
          plugin_habits_from: 1000
          config_timezone: America/New_York
          config_output: svg
          #`config_order: base.header, introduction, base.activity+community, base.repositories, base.metadata, languages, isocalendar, habits, habit_facts, habits_charts
          config_display: large
          optimize: svg
          experimental_features: --optimize-svg